apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: api
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        network/boilerplate_net: "true"
        service: api
    spec:
      containers:
      - env:
        - name: API_PORT
          value: "9000"
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: test_db
        - name: DB_PASSWORD
          value: your_pass
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: your_user
        - name: NODE_ENV
          value: test
        - name: TZ
          value: utc
        image: api
        imagePullPolicy: "Never"
        name: api
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
