apiVersion: v1
kind: Service
metadata:
  labels:
    service: fs-api
  name: fs-api-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    service: fs-api