apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: db
  name: db
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    service: db
status:
  loadBalancer: {}
